# Config file for automatic testing at travis-ci.org

branches:
 only:
  - master

language: python

matrix:
  include:
    - os: linux
      python: "3.4"
      env:
        - RUN=

    - os: linux
      python: "3.3"
      env:
        - RUN=

    - os: linux
      python: 2.7
      env:
        - RUN=

    - os: osx
      language: generic
      python: "3.4"
      env:
        - PYTHONVERSION=3.4.5 RUN=./ci/travis/run.bash

    - os: osx
      language: generic
      python: "3.3"
      env:
        - PYTHONVERSION=3.3.6 RUN=./ci/travis/run.bash

    - os: osx
      language: generic
      python: "2.7"
      env:
        - PYTHONVERSION=2.7.12 RUN=./ci/travis/run.bash

  allow_failures:
    - os: linux
      python: "3.3"

addons:
  apt:
    packages:
      - gfortran
      - libboost-python-dev
      - python-vtk

install:
  - python ci/driver.py travis install
  - $RUN python ci/driver.py travis style

script:
  - $RUN python ci/driver.py travis build
  - $RUN python ci/driver.py travis test

after_success:
  - $RUN python ci/driver.py travis after_test
