# Config file for automatic testing at travis-ci.org

branches:
 only:
  - master

language: python

matrix:
  include:
    - os: linux
      python: "3.4"

    - os: linux
      python: "3.3.5"

    - os: linux
      python: "2.7"

    - os: osx
      language: generic
      env:
        - PYTHONVERSION=3.4.5

    - os: osx
      language: generic
      env:
        - PYTHONVERSION=3.3.6

    - os: osx
      language: generic
      env:
        - PYTHONVERSION=2.7.12

cache:
  directories:
    - $HOME/.pyenv/versions/3.4.5
    - $HOME/.pyenv/versions/3.3.6
    - $HOME/.pyenv/versions/2.7.12
    - $HOME/downloads

addons:
  apt:
    packages:
      - gfortran
      - libboost-python-dev
      - python-vtk

before_install:
  - |
    git clone git://github.com/scikit-build/scikit-ci -b move-scripts-to-scikit-ci-addons ../bootstrap-scikit-ci
    pip install ../bootstrap-scikit-ci/
    git clone git://github.com/scikit-build/scikit-ci-addons ../ci

install:
  - ci before_install
  - ci install

before_script:
  - ci before_build

script:
  - ci build
  - ci test

after_success:
  - ci after_test
