# Config file for automatic testing at travis-ci.org

branches:
 only:
  - master

language: python

matrix:
  include:
    - os: linux
      python: "3.4"

    - os: linux
      python: "3.3"

    - os: linux
      python: "2.7"

    - os: osx
      language: generic
      python: "3.4"
      env:
        - PYTHONVERSION=3.4.5

    - os: osx
      language: generic
      python: "3.3"
      env:
        - PYTHONVERSION=3.3.6

    - os: osx
      language: generic
      python: "2.7"
      env:
        - PYTHONVERSION=2.7.12

  allow_failures:
    - os: linux
      python: "3.3"

addons:
  apt:
    packages:
      - gfortran
      - libboost-python-dev
      - python-vtk

install:
  - python ci/driver.py travis install
  - python ci/driver.py travis style

script:
  - python ci/driver.py travis build
  - python ci/driver.py travis test

after_success:
  - python ci/driver.py travis after_test
