---

# borrowed heavily from ogrisel/python-appveyor-demo

version: "0.0.1.{build}"

environment:
  matrix:
    ##################################################
    # NOTE: For now, Fortran features are not tested #
    ##################################################

    # Visual Studio (Python 2 & 3, 32 & 64 bit)
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "32"
      CMAKE_GENERATOR: Visual Studio 9 2008
      RUN: "cmd /E:ON /V:ON /C .\\ci\\appveyor\\run.cmd"
      EXTRA_TEST_ARGS: "--exclude fortran_compiler --exclude pen2 --exclude tbabel"
      SKIP: "0"
      BLOCK: "1"

    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "64"
      CMAKE_GENERATOR: Visual Studio 9 2008 Win64
      RUN: "cmd /E:ON /V:ON /C .\\ci\\appveyor\\run.cmd"
      EXTRA_TEST_ARGS: "--exclude fortran_compiler --exclude pen2 --exclude tbabel"
      SKIP: "1"

    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5.x"
      PYTHON_ARCH: "32"
      CMAKE_GENERATOR: Visual Studio 14 2015
      RUN: "cmd /E:ON /V:ON /C .\\ci\\appveyor\\run.cmd"
      EXTRA_TEST_ARGS: "--exclude fortran_compiler --exclude pen2 --exclude tbabel"
      SKIP: "1"

    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5.x"
      PYTHON_ARCH: "64"
      CMAKE_GENERATOR: Visual Studio 14 2015 Win64
      RUN: "cmd /E:ON /V:ON /C .\\ci\\appveyor\\run.cmd"
      EXTRA_TEST_ARGS: "--exclude fortran_compiler --exclude pen2 --exclude tbabel"
      SKIP: "1"

    # MinGW (Python 2 & 3, 64 bit only)
    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "64"
      CMAKE_GENERATOR: "MinGW Makefiles"
      RUN: "cmd /E:ON /V:ON /C .\\ci\\appveyor\\run.cmd"
      EXTRA_TEST_ARGS: "--exclude fortran_compiler --exclude pen2 --exclude tbabel"
      SKIP: "1"

    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5.x"
      PYTHON_ARCH: "32"
      CMAKE_GENERATOR: "MinGW Makefiles"
      RUN: "cmd /E:ON /V:ON /C .\\ci\\appveyor\\run.cmd"
      EXTRA_TEST_ARGS: "--exclude fortran_compiler --exclude pen2 --exclude tbabel"
      SKIP: "1"

    # Default -- make sure Visual Studio works as the default
    # (Python 2 & 3, 64 bit only)
    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "64"
      RUN: "cmd /E:ON /V:ON /C .\\ci\\appveyor\\run.cmd"
      EXTRA_TEST_ARGS: "--exclude fortran_compiler --exclude pen2 --exclude tbabel"
      SKIP: "1"

    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5.x"
      PYTHON_ARCH: "64"
      RUN: "cmd /E:ON /V:ON /C .\\ci\\appveyor\\run.cmd"
      EXTRA_TEST_ARGS: "--exclude fortran_compiler --exclude pen2 --exclude tbabel"
      SKIP: "1"

install:
  - cmd: "%PYTHON%\\python.exe .\\ci\\appveyor\\driver.py install"
  - cmd: "SET SKIP=1"

build_script:
  - cmd: "%RUN% %PYTHON%\\python.exe .\\ci\\appveyor\\driver.py build"

test_script:
  - cmd: "%RUN% %PYTHON%\\python.exe .\\ci\\appveyor\\driver.py test"

after_test:
  - cmd: "%RUN% %PYTHON%\\python.exe .\\ci\\appveyor\\driver.py after_test"

on_finish:
  # - cmd: "%RUN% %PYTHON%\\python.exe .\\ci\\appveyor\\driver.py on_finish"
  - cmd: "%PYTHON%\\python.exe .\\ci\\appveyor\\driver.py on_finish"

artifacts:
  # Archive the generated packages in the ci.appveyor.com build report.
  - path: dist\*

matrix:
  fast_finish: false

notifications:
  - provider: GitHubPullRequest
    auth_token:
      secure: iXYaAwXJcHdnRGTeb1Gk1PembhlZleCGDK2oJgsiFvA=
    template: >-
      {{#passed}}:white_check_mark:{{/passed}}{{#failed}}:x:{{/failed}}
      [Build {{&projectName}} {{buildVersion}} {{status}}]({{buildUrl}})
      (commit {{commitUrl}} by @{{&commitAuthorUsername}})

shallow_clone: true
