---

version: "0.0.1.{build}"

notifications:
  - provider: GitHubPullRequest
    auth_token:
      secure: iXYaAwXJcHdnRGTeb1Gk1PembhlZleCGDK2oJgsiFvA=
    template: >-
      {{#passed}}:white_check_mark:{{/passed}}{{#failed}}:x:{{/failed}}
      [Build {{&projectName}} {{buildVersion}} {{status}}]({{buildUrl}})
      (commit {{commitUrl}} by @{{&commitAuthorUsername}})

shallow_clone: true

environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python33"
    - PYTHON: "C:\\Python33-x64"
      DISTUTILS_USE_SDK: "1"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python34-x64"
      DISTUTILS_USE_SDK: "1"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python35-x64"

build: off

matrix:
  fast_finish: true

install:
  - cmd: >-
      %PYTHON%\python.exe -m pip install -U pip
  - cmd: >-
      %PYTHON%\python.exe -m pip install wheel
  - cmd: >-
      cinst cmake

before_test:
  - cmd: >-
      ci\build.cmd %PYTHON%\python.exe -m pip install -r requirements.txt
  - cmd: >-
      ci\build.cmd %PYTHON%\python.exe -m pip install -r requirements-dev.txt

test_script:
  - cmd: >-
      ci\build.cmd %PYTHON%\python.exe -m nose -w tests

after_test:
  - cmd: >-
      ci\build.cmd %PYTHON%\python.exe setup.py bdist_wheel

artifacts:
  - path: >-
      dist\*

