[build-system]
requires = ["setuptools>=42", "setuptools_scm[toml]"]
build-backend = "setuptools.build_meta"


[tool.setuptools_scm]
write_to = "skbuild/_version.py"


[tool.check-manifest]
ignore = [
  "skbuild/_version.py",
  "docs/**",
  ".*",
  "noxfile.py",
  "azure-pipelines.yml",
]


[tool.black]
line-length = 120


[tool.isort]
profile = "black"
known_third_party = ["distutils"]
force_to_top = ["setuptools"]

[tool.mypy]
files = ["skbuild"]
python_version = "3.6"
warn_unused_configs = true
check_untyped_defs = true
show_error_codes = true
enable_error_code = ["ignore-without-code", "redundant-expr", "truthy-bool"]
warn_unreachable = true



[tool.pylint]
master.py-version = "3.6"
master.jobs = "0"
reports.output-format = "colorized"
similarities.ignore-imports = "yes"
messages_control.enable = [
  "useless-suppression",
]
messages_control.disable = [
  "deprecated-module", # distutils usage
  "fixme",
  "invalid-name",
  "line-too-long",
  "missing-module-docstring",
  "no-member",
  "protected-access",
  "too-few-public-methods",
  "too-many-arguments",
  "too-many-branches",
  "too-many-locals",
  "too-many-statements",
  "ungrouped-imports",
  "wrong-import-order",
  "wrong-import-position",
]
