[build-system]
requires = ["setuptools>=42", "wheel", "setuptools_scm[toml]"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "skbuild/_version.py"


[tool.check-manifest]
ignore = [
  "skbuild/_version.py",
  "docs/**",
  ".*",
  "noxfile.py",
  "azure-pipelines.yml",
]
