name: CI

on:
  pull_request:
  push:
    branches:
    - master
    - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.3

  tests:
    runs-on: ${{ matrix.runs-on }}
    needs: [lint]
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-2016, windows-2022]

    name: Tests on ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set environment for available GHA MSVCs
      if: runner.os == 'Windows'
      run: |
        echo "SKBUILD_TEST_FIND_VS2008_INSTALLATION_EXPECTED=0" >> $GITHUB_ENV
        echo "SKBUILD_TEST_FIND_VS2010_INSTALLATION_EXPECTED=0" >> $GITHUB_ENV
        echo "SKBUILD_TEST_FIND_VS2012_INSTALLATION_EXPECTED=0" >> $GITHUB_ENV
        echo "SKBUILD_TEST_FIND_VS2015_INSTALLATION_EXPECTED=1" >> $GITHUB_ENV
        echo "SKBUILD_TEST_FIND_VS2017_INSTALLATION_EXPECTED=1" >> $GITHUB_ENV

    - name: Set environment for available GHA MSVCs
      if: matrix.runs-on == 'windows-2016'
      run: |
        echo "SKBUILD_TEST_FIND_VS2019_INSTALLATION_EXPECTED=0" >> $GITHUB_ENV
        echo "SKBUILD_TEST_FIND_VS2022_INSTALLATION_EXPECTED=0" >> $GITHUB_ENV

    - name: Set environment for available GHA MSVCs
      if: matrix.runs-on == 'windows-latest'
      run: |
        echo "SKBUILD_TEST_FIND_VS2019_INSTALLATION_EXPECTED=1" >> $GITHUB_ENV
        echo "SKBUILD_TEST_FIND_VS2022_INSTALLATION_EXPECTED=1" >> $GITHUB_ENV

    - name: Setup nox
      uses: excitedleigh/setup-nox@v2.0.0

    - name: Setup Python 3.10 dev
      uses: actions/setup-python@v2
      with:
        python-version: 3.10-dev

    # We check all Python's on Linux, because it's fast.
    # We check Python 2.7 on Linux and macOS, it's not supported on Windows.
    # We check minimum Python 3, and maximum Python 3 on all OS's.

    - name: Test on 🐍 2.7
      if: runner.os != 'Windows'
      run: nox --forcecolor -s tests-2.7
    - name: Test on 🐍 3.5
      if: matrix.runs-on != 'windows-latest'
      run: nox --forcecolor -s tests-3.5
    - name: Test on 🐍 3.6
      if: runner.os == 'Linux'
      run: nox --forcecolor -s tests-3.6
    - name: Test on 🐍 3.7
      if: runner.os == 'Linux'
      run: nox --forcecolor -s tests-3.7
    - name: Test on 🐍 3.8
      if: runner.os == 'Linux'
      run: nox --forcecolor -s tests-3.8
    - name: Test on 🐍 3.9
      run: nox --forcecolor -s tests-3.9
    - name: Test on 🐍 3.10
      run: nox --forcecolor -s tests-3.10

  # Split out due to a bug in our test suite requiring a clean run for Windows Ninja
  tests-win-extra:
    name: Tests on 🐍 3.5 • windows-latest
    runs-on: windows-latest
    needs: [lint]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set environment for available GHA MSVCs
      run: |
        echo "SKBUILD_TEST_FIND_VS2008_INSTALLATION_EXPECTED=0" >> $GITHUB_ENV
        echo "SKBUILD_TEST_FIND_VS2010_INSTALLATION_EXPECTED=0" >> $GITHUB_ENV
        echo "SKBUILD_TEST_FIND_VS2012_INSTALLATION_EXPECTED=0" >> $GITHUB_ENV
        echo "SKBUILD_TEST_FIND_VS2015_INSTALLATION_EXPECTED=1" >> $GITHUB_ENV
        echo "SKBUILD_TEST_FIND_VS2017_INSTALLATION_EXPECTED=1" >> $GITHUB_ENV
        echo "SKBUILD_TEST_FIND_VS2019_INSTALLATION_EXPECTED=1" >> $GITHUB_ENV

    - name: Setup nox
      uses: excitedleigh/setup-nox@v2.0.0

    - name: Test on 🐍 3.5
      run: nox --forcecolor -s tests-3.5


  dist:
    name: Distribution
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Build SDist and wheel
      run: pipx run build

    - uses: actions/upload-artifact@v2
      with:
        path: dist/*

    - name: Check metadata
      run: pipx run twine check dist/*
