# GitHub Action to automate the identification of common misspellings in text files.
# https://github.com/codespell-project/actions-codespell
# https://github.com/codespell-project/codespell
name: codespell

on:
  pull_request:
  push:
    branches:
    - master
    - main

jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: codespell-project/actions-codespell@master
        with:
          check_filenames: true
          skip: ".git,.pylintrc,*.png,*.svg,_version.py,versioneer.py"
          ignore_words_list: "ba,endwhile,unparseable"
